name: Ondrejlangr.cz frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Ondrejlangr.cz frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
      
      - name: Install deps
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      
      - name: Build project (RAM issue)
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Deploy to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@64.227.113.226:22/ondrej-fe'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          branch: 'main'
